# Generated by Django 3.0.5 on 2020-05-03 22:06

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('C', 'Chat')], default='C', max_length=1, verbose_name='?YPE')),
            ],
        ),
        migrations.CreateModel(
            name='Class_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date_of_record', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('subject_image', models.ImageField(upload_to='')),
                ('date_of_record', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects_overview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('over_view', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('video', models.FileField(upload_to='')),
                ('duration', models.DurationField(help_text='[DD] [HH:[MM:]]ss[.uuuuuu] format')),
                ('date_of_record', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.IntegerField(help_text='UGX')),
                ('class_n', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Class_table')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schools_taught', models.CharField(max_length=30)),
                ('current_school', models.CharField(max_length=30)),
                ('level_of_teaching', models.CharField(choices=[('O-Level', 'Ordinary level'), ('A-Level', 'Advanced level'), ('Both', 'Both levels')], max_length=30)),
                ('teacher_registration_id', models.CharField(max_length=100)),
                ('subject_one', models.CharField(choices=[('Mathematics', 'Mathatics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('History', 'History'), ('Geography', 'Geography'), ('English', 'English'), ('Islam', 'Islam'), ('CRE', 'CRE'), ('Agriculture', 'Agriculture'), ('Computer', 'Computer'), ('TechnicalDrawing', 'TechnicalDrawing'), ('Art', 'Art'), ('French', 'French'), ('German', 'German'), ('Chinese', 'Chinese'), ('Luganda', 'Luganda'), ('GeneralPaper', 'GeneralPaper')], max_length=20)),
                ('subject_two', models.CharField(choices=[('Mathematics', 'Mathatics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('History', 'History'), ('Geography', 'Geography'), ('English', 'English'), ('Islam', 'Islam'), ('CRE', 'CRE'), ('Agriculture', 'Agriculture'), ('Computer', 'Computer'), ('TechnicalDrawing', 'TechnicalDrawing'), ('Art', 'Art'), ('French', 'French'), ('German', 'German'), ('Chinese', 'Chinese'), ('Luganda', 'Luganda'), ('GeneralPaper', 'GeneralPaper')], max_length=20)),
                ('Brief_Self_description', models.TextField()),
                ('date_of_record', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=20)),
                ('location', models.CharField(max_length=30)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(default='default.png', upload_to='')),
                ('date_of_birth', models.DateTimeField(null=True)),
                ('role', models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('User', 'User')], default='User', max_length=8)),
                ('date_of_record', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Upload_topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.CharField(max_length=60)),
                ('subject', models.CharField(max_length=60)),
                ('topic', models.CharField(max_length=900)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('videos', models.FileField(upload_to='')),
                ('attached_file', models.FileField(upload_to='')),
                ('date_of_record', models.DateTimeField(default=django.utils.timezone.now)),
                ('overview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Subjects_overview')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Teacher_apply')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalDrawing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=30)),
                ('date_of_record', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_n', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Class_table')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Subjects')),
            ],
        ),
        migrations.AddField(
            model_name='teacher_apply',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.UserProfile'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField()),
                ('active', models.BooleanField(default=False)),
                ('date_of_subscription', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.DurationField()),
                ('class_n', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Class_table')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Subjects')),
                ('subject_overview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Subjects_overview')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Teacher_apply')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='subjects_overview',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Teacher_apply'),
        ),
        migrations.CreateModel(
            name='Physics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=30)),
                ('date_of_record', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_n', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Class_table')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Subjects')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField()),
                ('active', models.BooleanField(default=False)),
                ('date_of_subscription', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.DurationField()),
                ('class_n', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Class_table')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Subjects')),
                ('subject_overview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Subjects_overview')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Teacher_apply')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Message date')),
                ('is_readed', models.BooleanField(default=False, verbose_name='Readed')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Chat', verbose_name='Chat')),
            ],
            options={
                'ordering': ['pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Mathematics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=30)),
                ('date_of_record', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_n', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Class_table')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Luganda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=30)),
                ('date_of_record', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_n', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Class_table')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Islam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=30)),
                ('date_of_record', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_n', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Class_table')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Subjects')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=30)),
                ('date_of_record', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_n', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Class_table')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Subjects')),
            ],
        ),
        migrations.CreateModel(
            name='German',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=30)),
                ('date_of_record', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_n', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Class_table')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=30)),
                ('date_of_record', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_n', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Class_table')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Subjects')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=30)),
                ('date_of_record', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_n', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Class_table')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Subjects')),
            ],
        ),
        migrations.CreateModel(
            name='French',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=30)),
                ('date_of_record', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_n', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Class_table')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Subjects')),
            ],
        ),
        migrations.CreateModel(
            name='English',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=30)),
                ('date_of_record', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_n', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Class_table')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Subjects')),
            ],
        ),
        migrations.CreateModel(
            name='CRE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=30)),
                ('date_of_record', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_n', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Class_table')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=30)),
                ('date_of_record', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_n', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Class_table')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='e_learning.Comment')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='e_learning.Upload_topics')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Chinese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=30)),
                ('date_of_record', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_n', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Class_table')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Chemistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=30)),
                ('date_of_record', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_n', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Class_table')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Subjects')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_message', to='e_learning.Message'),
        ),
        migrations.AddField(
            model_name='chat',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Member'),
        ),
        migrations.CreateModel(
            name='Biology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=30)),
                ('date_of_record', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_n', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Class_table')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=30)),
                ('date_of_record', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_n', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Class_table')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Agriculture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=30)),
                ('date_of_record', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_n', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Class_table')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Subjects')),
            ],
        ),
    ]
