# Generated by Django 3.0.5 on 2020-05-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_learning', '0002_auto_20200504_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='members',
            field=models.ManyToManyField(to='e_learning.Teacher_apply', verbose_name='Member'),
        ),
    ]
