# Generated by Django 3.0.5 on 2020-05-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_learning', '0004_auto_20200520_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects_overview',
            name='duration',
            field=models.DurationField(help_text='[DD] [HH:[MM:]]ss[.uuuuuu] format---- eg 30 00:00 to'),
        ),
    ]
