# Generated by Django 3.0.6 on 2020-05-23 09:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('e_learning', '0006_auto_20200520_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend_Subjects_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('class_level', models.CharField(max_length=30)),
                ('book_title', models.CharField(max_length=30)),
                ('book_cover_image', models.ImageField(upload_to='')),
                ('attach_book', models.FileField(upload_to='')),
                ('recommended_by', models.CharField(max_length=30)),
                ('date_of_record', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
