# Generated by Django 3.0.5 on 2020-06-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_learning', '0008_chatcomment_chatroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_image',
            field=models.CharField(default='default.png', max_length=800),
        ),
    ]
