# Generated by Django 3.0.5 on 2020-06-06 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_learning', '0010_auto_20200605_0251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
    ]
