# Generated by Django 3.0.5 on 2020-06-07 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_learning', '0012_studentchatcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentchatcomment',
            options={'ordering': ['-created_on']},
        ),
    ]
