# Generated by Django 3.0.5 on 2020-06-07 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_learning', '0013_auto_20200607_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatcomment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
    ]
