# Generated by Django 3.0.5 on 2020-06-13 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('e_learning', '0015_recommend_subjects_table_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend_subjects_table',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacher_apply',
            name='subject_one',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('History', 'History'), ('Geography', 'Geography'), ('English', 'English'), ('Islam', 'Islam'), ('CRE', 'CRE'), ('Agriculture', 'Agriculture'), ('Computer', 'Computer'), ('Economics', 'Economics'), ('Divinity', 'Divinity'), ('Literature', 'Literature'), ('TechnicalDrawing', 'TechnicalDrawing'), ('Art', 'Art'), ('French', 'French'), ('German', 'German'), ('Lugbara_Ti', 'Lugbara_Ti'), ('Chinese', 'Chinese'), ('Luganda', 'Luganda'), ('GeneralPaper', 'GeneralPaper')], max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher_apply',
            name='subject_two',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('History', 'History'), ('Geography', 'Geography'), ('English', 'English'), ('Islam', 'Islam'), ('CRE', 'CRE'), ('Agriculture', 'Agriculture'), ('Computer', 'Computer'), ('Economics', 'Economics'), ('Divinity', 'Divinity'), ('Literature', 'Literature'), ('TechnicalDrawing', 'TechnicalDrawing'), ('Art', 'Art'), ('French', 'French'), ('German', 'German'), ('Lugbara_Ti', 'Lugbara_Ti'), ('Chinese', 'Chinese'), ('Luganda', 'Luganda'), ('GeneralPaper', 'GeneralPaper')], max_length=20),
        ),
        migrations.CreateModel(
            name='Lugbara_Ti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=30)),
                ('date_of_record', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_n', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Class_table')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=30)),
                ('date_of_record', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_n', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Class_table')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Economics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=30)),
                ('date_of_record', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_n', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Class_table')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Divinity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=30)),
                ('date_of_record', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_n', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Class_table')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Subjects')),
            ],
        ),
    ]
