# Generated by Django 3.0.5 on 2020-06-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_learning', '0016_auto_20200613_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agriculture',
            name='topic_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='art',
            name='topic_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='biology',
            name='topic_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='chemistry',
            name='topic_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='chinese',
            name='topic_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='computer',
            name='topic_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='cre',
            name='topic_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='divinity',
            name='topic_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='economics',
            name='topic_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='english',
            name='topic_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='french',
            name='topic_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='generalpaper',
            name='topic_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='geography',
            name='topic_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='german',
            name='topic_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='history',
            name='topic_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='islam',
            name='topic_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='literature',
            name='topic_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='luganda',
            name='topic_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='lugbara_ti',
            name='topic_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='mathematics',
            name='topic_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='physics',
            name='topic_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='teacher_apply',
            name='subject_one',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('History', 'History'), ('Geography', 'Geography'), ('English', 'English'), ('Islam', 'Islam'), ('Cre', 'Cre'), ('Agriculture', 'Agriculture'), ('Computer', 'Computer'), ('Economics', 'Economics'), ('Divinity', 'Divinity'), ('Literature', 'Literature'), ('TechnicalDrawing', 'TechnicalDrawing'), ('Art', 'Art'), ('French', 'French'), ('German', 'German'), ('Lugbara_Ti', 'Lugbara_Ti'), ('Chinese', 'Chinese'), ('Luganda', 'Luganda'), ('GeneralPaper', 'GeneralPaper')], max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher_apply',
            name='subject_two',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('History', 'History'), ('Geography', 'Geography'), ('English', 'English'), ('Islam', 'Islam'), ('Cre', 'Cre'), ('Agriculture', 'Agriculture'), ('Computer', 'Computer'), ('Economics', 'Economics'), ('Divinity', 'Divinity'), ('Literature', 'Literature'), ('TechnicalDrawing', 'TechnicalDrawing'), ('Art', 'Art'), ('French', 'French'), ('German', 'German'), ('Lugbara_Ti', 'Lugbara_Ti'), ('Chinese', 'Chinese'), ('Luganda', 'Luganda'), ('GeneralPaper', 'GeneralPaper')], max_length=20),
        ),
        migrations.AlterField(
            model_name='technicaldrawing',
            name='topic_name',
            field=models.CharField(max_length=300),
        ),
    ]
