# Generated by Django 3.0.5 on 2020-07-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_learning', '0017_auto_20200626_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_topics',
            name='videos',
            field=models.FileField(blank=True, default='comingsoon_topic.mp4', null=True, upload_to=''),
        ),
    ]
