# Generated by Django 3.0.5 on 2020-07-16 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('e_learning', '0018_auto_20200702_0416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_title', models.CharField(max_length=300)),
                ('attach_assignment', models.FileField(upload_to='')),
                ('date_of_record', models.DateTimeField(default=django.utils.timezone.now)),
                ('subject_overview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Subjects_overview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
