# Generated by Django 3.0.5 on 2020-07-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_learning', '0019_assignments_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend_subjects_table',
            name='book_cover_image',
            field=models.ImageField(blank=True, default='book_vector.png', null=True, upload_to=''),
        ),
    ]
