# Generated by Django 3.0.6 on 2020-07-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_learning', '0020_auto_20200717_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend_subjects_table',
            name='book_cover_image',
            field=models.ImageField(default='book_vector.png', upload_to=''),
        ),
    ]
