# Generated by Django 3.0.5 on 2020-07-17 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('e_learning', '0021_auto_20200717_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_response', models.FileField(upload_to='')),
                ('date_of_record', models.DateTimeField(default=django.utils.timezone.now)),
                ('assignments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_learning.Assignments_Table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
